### PR TITLE
Update the selection color

### PR DESCRIPTION
**Pull request by pwbzh**
Hello,

Currently, when the `Highlight current line` option is enable in Gedit preferences, the `selection` color from the theme is the same as the highlight color.

Thanks for your great job!

### CODE REVIEW

**Comment by richin13** [comment]
Hey @jesuispw, 

Thank you very much for the PR and congrats for the first-time contribution to the repo. Be very welcome.

As soon as I get home, I'll check the PR and proceed to merge.

Regards.

**Comment by richin13** [comment]
Hello, I checked the theme and there's indeed an issue with the selection color. Thanks for poiting that out.
I am merging this, but before I need you to do a little change: First, check the official color palette (https://github.com/dracula/dracula-theme#color-palette) and choose a color that fits with the rest of theme, commit the changes to this same PR and we'll be ready to go.

Regards

**Comment by pwbzh** [comment]
Hello,

Thanks for your feedback. So, I suggest a new color from the color palette.

Regards

**Comment by richin13** [comment]
Hello, I am getting this result :-(

captura de pantalla de 2017-09-06 21-00-41

Can you try something else? Maybe purple?

Regards

**Comment by pwbzh** [comment]
Hello,

I don't have this problem but I changed the color to purple.

indigo

Regards

**Pull request merged**
